# Generated by Django 5.2.1 on 2026-03-19 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_id_barsianalysis_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barsianalysis',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barsi_analyses', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='GrahamAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fair_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graham_analyses', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Análise Graham',
                'verbose_name_plural': 'Análises Graham',
                'ordering': ['-created_at'],
            },
        ),
    ]
