# Generated by Django 5.2.1 on 2026-03-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_barsianalysis_asset_grahamanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grahamanalysis',
            name='growth_rate',
        ),
        migrations.AddField(
            model_name='grahamanalysis',
            name='vpa',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
            preserve_default=False,
        ),
    ]
