# Generated by Django 5.2.1 on 2026-03-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_id_alter_barsianalysis_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['ticker'], 'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterModelOptions(
            name='barsianalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Análise Barsi', 'verbose_name_plural': 'Análises Barsi'},
        ),
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Dividendo', 'verbose_name_plural': 'Dividendos'},
        ),
    ]
