# Generated by Django 5.2.1 on 2026-04-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_options_alter_barsianalysis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grahamanalysis',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='projectedanalysis',
            name='asset',
        ),
        migrations.AlterModelTable(
            name='asset',
            table='assets_asset',
        ),
        migrations.AlterModelTable(
            name='dividend',
            table='assets_dividend',
        ),
        migrations.DeleteModel(
            name='BarsiAnalysis',
        ),
        migrations.DeleteModel(
            name='GrahamAnalysis',
        ),
        migrations.DeleteModel(
            name='ProjectedAnalysis',
        ),
    ]
