# Generated by Django 5.2.1 on 2026-04-27 17:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_grahamanalysis_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='annual_dividend',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, default='BRL', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='data_source',
            field=models.CharField(blank=True, default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Dividend yield em formato decimal. Ex: 0.06 = 6%', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lpa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='payout_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='vpa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='dividend',
            constraint=models.UniqueConstraint(fields=('asset', 'payment_date'), name='unique_dividend_per_asset_date'),
        ),
    ]
