# Generated by Django 5.2.1 on 2026-03-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_grahamanalysis_growth_rate_grahamanalysis_vpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barsianalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grahamanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProjectedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average_dividend_yield', models.DecimalField(decimal_places=4, max_digits=5)),
                ('raw_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ceiling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_analyses', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Análise Projetiva',
                'verbose_name_plural': 'Análises Projetivas',
                'ordering': ['-created_at'],
            },
        ),
    ]
