version: "3.9"

services:
  db:
    image: postgres:15
    container_name: investsmart_db
    restart: always
    environment:
      POSTGRES_DB: investsmart
      POSTGRES_USER: investsmart_user
      POSTGRES_PASSWORD: investsmart_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: