sonar.projectKey=LucasCarvalhoSteffens_InvestSmart
sonar.organization=lucascarvalhosteffens
sonar.projectName=InvestSmart
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# =========================
# Sources
# =========================
sonar.sources=backend/apps,backend/config,backend/core,frontend/src

# =========================
# Tests
# =========================
sonar.tests=backend/apps,backend/core,frontend/src/test

sonar.test.inclusions=backend/apps/**/tests/**/*.py,backend/core/tests.py,frontend/src/test/**/*.test.js,frontend/src/test/**/*.test.jsx

# =========================
# Exclusions
# =========================
sonar.exclusions=backend/**/migrations/**,backend/apps/**/tests/**,backend/core/tests.py,backend/config/asgi.py,backend/config/wsgi.py,backend/config/settings_test.py,frontend/src/test/**,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx,frontend/node_modules/**,frontend/dist/**,frontend/coverage/**

sonar.coverage.exclusions=backend/**/migrations/**,backend/config/asgi.py,backend/config/wsgi.py,backend/config/settings_test.py,backend/**/__init__.py,backend/apps/accounts/urls.py,frontend/src/main.jsx,frontend/src/test/**,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx

# =========================
# Python coverage
# =========================
sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml

# =========================
# JavaScript / React coverage
# =========================
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info