sonar.projectKey=LucasCarvalhoSteffens_InvestSmart
sonar.organization=lucascarvalhosteffens
sonar.projectName=InvestSmart
sonar.projectVersion=1.0

sonar.sources=backend/apps,backend/config,backend/core
sonar.tests=backend/apps,backend/core

sonar.test.inclusions=backend/apps/**/tests/**/*.py,backend/core/tests.py
sonar.exclusions=backend/**/migrations/**,backend/apps/**/tests/**,backend/core/tests.py,backend/config/asgi.py,backend/config/wsgi.py,backend/config/settings_test.py

sonar.coverage.exclusions=backend/**/migrations/**,backend/config/asgi.py,backend/config/wsgi.py,backend/config/settings_test.py,backend/**/__init__.py,backend/apps/accounts/urls.py

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=backend/coverage.xml