# Generated by Django 5.2.1 on 2026-04-16 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0007_remove_grahamanalysis_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'db_table': 'portfolios_portfolio',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='assets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Item da Carteira',
                'verbose_name_plural': 'Itens da Carteira',
                'db_table': 'portfolios_portfolioitem',
                'ordering': ['portfolio__name', 'asset__ticker'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('below_or_equal', 'Preço menor ou igual'), ('above_or_equal', 'Preço maior ou igual')], max_length=20)),
                ('threshold_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolios.portfolioitem')),
            ],
            options={
                'verbose_name': 'Alerta do Item',
                'verbose_name_plural': 'Alertas do Item',
                'db_table': 'portfolios_portfolioitemalert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_portfolio_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='portfolioitem',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='unique_asset_per_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='portfolioitemalert',
            constraint=models.UniqueConstraint(fields=('portfolio_item', 'alert_type', 'threshold_price'), name='unique_alert_per_item_type_threshold'),
        ),
    ]
