# Generated by Django 5.2.1 on 2026-04-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('below_or_equal_ceiling', 'Preço abaixo ou igual ao preço teto'), ('above_ceiling', 'Preço acima do preço teto')], max_length=40)),
                ('price_ceiling', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_ceiling_source', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='portfolios.portfolioitem')),
            ],
            options={
                'verbose_name': 'Evento de Alerta',
                'verbose_name_plural': 'Eventos de Alerta',
                'db_table': 'portfolios_portfolioalertevent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='portfolios__event_t_62b420_idx'), models.Index(fields=['is_read', 'created_at'], name='portfolios__is_read_0c7811_idx')],
            },
        ),
    ]
