# Generated by Django 5.2.1 on 2026-04-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0007_remove_grahamanalysis_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarsiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_dividend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_yield', models.DecimalField(decimal_places=4, default=0.06, max_digits=5)),
                ('price_ceiling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opportunity', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barsi_analyses', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Análise Barsi',
                'verbose_name_plural': 'Análises Barsi',
                'db_table': 'assets_barsianalysis',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrahamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fair_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graham_analyses', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Análise Graham',
                'verbose_name_plural': 'Análises Graham',
                'db_table': 'assets_grahamanalysis',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dpa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average_dividend_yield', models.DecimalField(decimal_places=4, max_digits=5)),
                ('raw_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ceiling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_analyses', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Análise Projetiva',
                'verbose_name_plural': 'Análises Projetivas',
                'db_table': 'assets_projectedanalysis',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
